services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fts-upload-server
    ports:
      - "2999:2999"
    volumes:
      - ./uploads:/app/uploads
      - ./config.json:/app/config.json:ro
      - ./server.log:/app/server.log
    restart: unless-stopped
